version: "3.9"

services:
  diffbot-small:
    image: diffbot-small
    ports:
      - "5722:5000"
    environment:
      - TZ=${TZ:-Europe/Luxembourg}
      - NVIDIA_VISIBLE_DEVICES=all
      - PORT=5000
    runtime: nvidia
    restart: always
    networks:
      - arch-network

networks:
  arch-network:
    driver: "bridge"